"""
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib_seq_sync():
    solution = 0
    current = 1
    after = 2
    while current <= 4000000:
        if current % 2 == 0:
            solution += current
        current, after = after, current + after
    
    print(solution)


fib_seq_sync()
# 4613732


